-- Homepage (uses the same section config as default-config.ts)
INSERT INTO site_pages (id, slug, title, description, sections, status, show_in_nav, sort_order) VALUES
(gen_random_uuid(), 'home', 'Home', 'Build Your SaaS Faster with MuseKit', '[
  {"type":"hero","enabled":true,"sortOrder":1,"props":{"style":"pattern","headline":"Build Your SaaS Faster","subheadline":"MuseKit is the complete SaaS starter kit. Authentication, billing, admin tools, email, AI, and a full CMS — all wired up and ready to customize.","ctaText":"Get Started","ctaLink":"/signup","secondaryCtaText":"Learn More","secondaryCtaLink":"/features"}},
  {"type":"feature-cards","enabled":true,"sortOrder":2,"props":{"title":"Everything You Need to Launch","subtitle":"Stop piecing together boilerplate.","columns":3,"features":[{"icon":"Shield","title":"Auth & Users","description":"Secure authentication with email, social logins, and role-based access control."},{"icon":"CreditCard","title":"Billing & Subscriptions","description":"Stripe integration with subscription plans, usage-based billing, and invoices."},{"icon":"LayoutDashboard","title":"Admin Dashboard","description":"A full admin panel for managing users, content, settings, and analytics."},{"icon":"Mail","title":"Email System","description":"Transactional email templates for onboarding, notifications, and marketing."},{"icon":"Sparkles","title":"AI Integration","description":"Built-in AI-powered tools for content generation and automated workflows."},{"icon":"FileText","title":"Blog & CMS","description":"Complete content management with a markdown blog, landing page builder, and SEO tools."}]}},
  {"type":"process-steps","enabled":true,"sortOrder":3,"props":{"title":"Get Started in Minutes","subtitle":"Go from zero to a fully functional SaaS application in four steps.","steps":[{"title":"Clone the Repo","description":"Get the entire MuseKit codebase with a single command."},{"title":"Configure Your Settings","description":"Set environment variables, connect Supabase and Stripe."},{"title":"Customize the Design","description":"Tailor branding with the design system — colors, typography, and styles."},{"title":"Launch Your Product","description":"Deploy to production with secure defaults and monitoring built in."}]}},
  {"type":"testimonial-carousel","enabled":true,"sortOrder":4,"props":{"testimonials":[{"quote":"MuseKit saved us at least three months of development time.","name":"Sarah Chen","role":"CTO","company":"Pairwise Labs"},{"quote":"The modular architecture is brilliant.","name":"Marcus Rivera","role":"Lead Engineer","company":"Northwind Digital"},{"quote":"Finally, a starter kit that feels production-ready from day one.","name":"Priya Sharma","role":"Founder","company":"Canopy Analytics"}]}},
  {"type":"faq","enabled":true,"sortOrder":5,"props":{"title":"Frequently Asked Questions","faqs":[{"question":"What is MuseKit?","answer":"MuseKit is a complete SaaS starter kit with auth, billing, admin, email, AI, and CMS."},{"question":"What tech stack does it use?","answer":"Next.js 14, React 18, TypeScript, Tailwind CSS, Supabase, and Stripe."},{"question":"Is it production-ready?","answer":"Yes. MuseKit ships with secure defaults, RBAC, validation, and error handling."}]}},
  {"type":"bottom-hero-cta","enabled":true,"sortOrder":6,"props":{"headline":"Ready to Launch?","subheadline":"Stop rebuilding infrastructure. Start with MuseKit.","ctaText":"Start Building","ctaLink":"/signup"}}
]'::jsonb, 'published', false, 0)
ON CONFLICT (slug) DO NOTHING;
-- About page
INSERT INTO site_pages (id, slug, title, description, sections, status, show_in_nav, sort_order) VALUES
(gen_random_uuid(), 'about', 'About Us', 'Learn about the team behind MuseKit', '[
  {"type":"hero","enabled":true,"sortOrder":1,"props":{"style":"gradient","headline":"About MuseKit","subheadline":"We build tools that help developers ship faster.","ctaText":"Join Us","ctaLink":"/signup"}},
  {"type":"founder-letter","enabled":true,"sortOrder":2,"props":{"name":"Alex Morgan","title":"Founder & CEO","letter":"We started MuseKit because we were tired of rebuilding the same SaaS infrastructure for every project. Authentication, billing, admin dashboards, email systems — they are table stakes, not differentiators. We built MuseKit so you can focus on what makes your product unique."}},
  {"type":"image-text-blocks","enabled":true,"sortOrder":3,"props":{"blocks":[{"image":"","headline":"Our Mission","description":"Make SaaS development accessible to everyone by providing a production-grade foundation.","layout":"image-left"},{"image":"","headline":"Our Values","description":"Open source, developer-first, and built for scale. Every decision we make starts with the developer experience.","layout":"image-right"}]}},
  {"type":"bottom-hero-cta","enabled":true,"sortOrder":4,"props":{"headline":"Join the Community","subheadline":"Thousands of developers build with MuseKit.","ctaText":"Get Started","ctaLink":"/signup"}}
]'::jsonb, 'published', true, 1)
ON CONFLICT (slug) DO NOTHING;
-- Features page
INSERT INTO site_pages (id, slug, title, description, sections, status, show_in_nav, sort_order) VALUES
(gen_random_uuid(), 'features', 'Features', 'Everything included in MuseKit', '[
  {"type":"hero","enabled":true,"sortOrder":1,"props":{"style":"pattern","headline":"Everything You Need","subheadline":"A complete SaaS foundation with every feature built in.","ctaText":"Start Free","ctaLink":"/signup"}},
  {"type":"feature-cards","enabled":true,"sortOrder":2,"props":{"title":"Core Features","subtitle":"Production-ready modules you can adopt incrementally.","columns":3,"features":[{"icon":"Shield","title":"Authentication","description":"Email, social login, magic links, and role-based access control."},{"icon":"CreditCard","title":"Billing","description":"Stripe subscriptions, usage billing, invoices, and customer portal."},{"icon":"LayoutDashboard","title":"Admin Panel","description":"User management, analytics, content editing, and system settings."},{"icon":"Mail","title":"Email","description":"Transactional templates, campaigns, and delivery tracking."},{"icon":"Globe","title":"CMS","description":"Blog, landing pages, changelog, and media library."},{"icon":"Users","title":"Affiliate Program","description":"Full affiliate management with tiers, payouts, and tracking."}]}},
  {"type":"comparison-bars","enabled":true,"sortOrder":3,"props":{"title":"Build Faster","subtitle":"Compare development time with and without MuseKit.","beforeLabel":"Without MuseKit","afterLabel":"With MuseKit","comparisons":[{"label":"Auth System","before":80,"after":5,"unit":"hours"},{"label":"Billing Integration","before":120,"after":8,"unit":"hours"},{"label":"Admin Dashboard","before":200,"after":10,"unit":"hours"},{"label":"Email System","before":60,"after":4,"unit":"hours"}]}},
  {"type":"bottom-hero-cta","enabled":true,"sortOrder":4,"props":{"headline":"Ready to Build?","subheadline":"Get started in minutes, not months.","ctaText":"Start Free","ctaLink":"/signup"}}
]'::jsonb, 'published', true, 2)
ON CONFLICT (slug) DO NOTHING;
